### ISSUE TITLE
license

### ISSUE THREAD

**Issue by thorade** [ORNL-Modelica/TRANSFORM-Library#24]
In the ReadMe, you mention the Modelica License, but just recently, the Modelica Association has switched to the BSD 3-clause license:
https://github.com/modelica/ModelicaStandardLibrary/issues/2320

Maybe you could also consider switching to that license, or any other OSI certified license?
https://choosealicense.com/appendix/
https://opensource.org/licenses

If you indeed decide to switch to an OSI certified license, you should also convert the License.pdf file into a License.md or License.txt file (also see #1) so that it is text based and not binary and tools can read it.
https://blog.github.com/2017-11-03-search-repositories-by-license/

**Comment by ORNL-Modelica** [comment]
I updated the MSL license reference. Thanks. 

Unfortunately I am constrained to the UT-Battelle license. However, I'm permitted to change to a .md/.txt format which I did.
