### ISSUE TITLE
Duplicated code from MSL

### ISSUE THREAD

**Issue by beutlich** [ORNL-Modelica/TRANSFORM-Library#44]
TRANSFORM.Media.Interfaces.Fluids contains duplicated code from Modelica.Media.Interfaces. Despite being a good modeling practice, the real issue is, that it cannot be handled by automatic conversion (to upcoming MSL v4.0.0), as reported in https://github.com/modelica/ModelicaStandardLibrary/issues/3384#issuecomment-584132976.

**Comment by greenwoodms06** [comment]
Alright. Thanks for pointing this out. I'll hold off on making any changes until MSL v4 is released in Dymola. I'll then address the issue.

And yes, my media had to diverge from MSL BaseProperties, I'm not just duplicating code willy nilly 😉  At least trying not too!

**Comment by beutlich** [comment]
Basically, you need to address the renaming from R to R_s for the specific gas constant.

**Comment by greenwoodms06** [comment]
Yup. Understood.

**Comment by greenwoodms06** [comment]
This should now be fixed with the MSL 4.0 update.
