### ISSUE TITLE
Compatibility with OpenModelica & Windows 10

### ISSUE THREAD

**Issue by Ciobrelis** [ORNL-Modelica/TRANSFORM-Library#61]
### Describe the bug
First of all, I would like to know if the library is or will be compatible with OpenModelica and Windows? If not, then you can ignore the rest.

I tried loading library with OpenModelica v1.16-0 (64-bit) on Windows 10 but it cannot load due to the issues with two models in the _"TRANSFORM/Fluid/Machines/BaseClasses/PumpCharacteristics/HomologousSets/"_ folder. Particularly the problem is caused by _“Axial.mo” & “Mixed.mo”_. 

> [1] 17:15:03 Syntax Error
[D:/Program_files/OpenModelica1.16.0/lib/omlibrary/TRANSFORM/Fluid/Machines/BaseClasses/PumpCharacteristics/HomologousSets/Mixed.mo: 45:7-45:16]: Subscripting modifiers is not allowed. Apply the modification on the whole identifier using an array-expression or an each-modifier.

> [2] 17:15:03 Syntax Error
> [D:/Program_files/OpenModelica1.16.0/lib/omlibrary/TRANSFORM/Fluid/Machines/BaseClasses/PumpCharacteristics/HomologousSets/Axial.mo: 45:7-45:16]: Subscripting modifiers is not allowed. Apply the modification on the whole identifier using an array-expression or an each-modifier.
> 
> [3] 17:15:03 Scripting Error
> Failed to load package TRANSFORM (default) using MODELICAPATH D:/Program_files/OpenModelica1.16.0/lib/omlibrary;C:/Users/Eddy/AppData/Roaming/.openmodelica/libraries/.

I think the problem is caused by the dimensions of arrays in the list, were the number of elements are not the same. e.g. `table_BAN=[0,0.539726027; 0.222147028, 0.608219178; 0.454467063, 
      0.712328767; 0.698935764, 0.832876712; 1,0.95890411]`

The same error was previously discussed [here](https://trac.openmodelica.org/OpenModelica/ticket/2663), and the advise was made to refer to [Modelica Specification](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#modifiers-for-array-elements) - _7.2.5 Modifiers for Array Elements_.

Nevertheless, I tried deleting “Axial.mo” & “Mixed.mo” and then library loads, but the following messages occur: 

> [1] 17:17:57 Grammar Warning
> [D:/Program_files/OpenModelica1.16.0/lib/omlibrary/TRANSFORM/Fluid/Machines/BaseClasses/PumpCharacteristics/HomologousSets/package.mo: 2:1-10:19]: Axial was referenced in the package.order file, but was not found in package.mo, Axial/package.mo or Axial.mo.
> 
> [2] 17:17:57 Scripting Warning
> Requested package ModelicaServices of version 3.2.2, but this package was already loaded with version 3.2.3. You might experience problems if these versions are incompatible.
> 
> [3] 17:17:57 Scripting Notification
> Skipped loading package UserInteraction (0.65,default) using MODELICAPATH D:/Program_files/OpenModelica1.16.0/lib/omlibrary;C:/Users/Eddy/AppData/Roaming/.openmodelica/libraries/ (uses-annotation may be wrong).
> 
> [4] 17:17:57 Scripting Notification
> You can install the requested package using one of the commands:
>   installPackage(SDF, "master", exactMatch=true)
>   installPackage(SDF, "0.4.1", exactMatch=false)
>   installPackage(SDF, "0.4.1", exactMatch=false).
> 
> [5] 17:17:57 Scripting Notification
> Skipped loading package SDF (0.4.1,default) using MODELICAPATH D:/Program_files/OpenModelica1.16.0/lib/omlibrary;C:/Users/Eddy/AppData/Roaming/.openmodelica/libraries/ (uses-annotation may be wrong).

The first message occurs as expected due to the missing *.mo files, but at least the library can be loaded. 
Messages from 3 to 5 occur only when I am using TRANSFORM library. 

Also, maybe problems can be caused by the installation location of the software, which is not default. Besides aforementioned problems there are plenty more, which are caused when trying to run test and other models. 

### Screenshots
Errors after initial try to load the library.
![image](https://user-images.githubusercontent.com/34867742/89131460-3e9d2a80-d50d-11ea-9f80-023985ec2e27.png)
After deleting “Axial.mo” & “Mixed.mo” library loads, but the following messages occur: 
![image](https://user-images.githubusercontent.com/34867742/89131476-65f3f780-d50d-11ea-8f92-d7e9cda6e559.png)

### Computer Configuration:**
 - OS: Windows 10
 - Modelica IDE and version: OpenModelica v1.16-0 (64-bit)
 
### Additional 
It would be beneficial if a compiled GNU GSL library would be by default in "TRANSFORM/Resources/Library/OSVERSION", were currently no "win64" folder exists and for an amateur user it might take considerable time to figure out how to accomplish it.

**Comment by greenwoodms06** [comment]
Hello,

**Homologous**
OpenModelica (OM) is not supported at this time. OM has issues that are supposedly being addressed (e.g., replaceable models) with the development of v2. Until that version comes out we will not be able to revisit OM internally but we don't intend to have Dymola specific capabilities. 

The issue you described seems different than the ticket issue. As I read that problem described in the specification it sounded more like distributing variables and extends-inception variation on that. As I look at the HomologousSets, that is a very vanilla situation. Underlying data with varying lengths. That should not be an issue unless I am misunderstanding.

I did check that package with pedantic mode enabled in Dymola and there were no issues. So there isn't anything I can do at this time.

**UserInteraction**
The userinteraction library is (I believe) from Dymola itself. It is only used in a couple examples so you will get a warning but it will not cause any general issues. This is something we will address when we support OM.

**GNU GSL**
Yes it would be greatto have it all compiled, however there are potential issues with copyright due to GSL's license which I don't believe I can include the compile GSL. I do hope that this is something we can address at some point in the future.

**Comment by greenwoodms06** [comment]
Wanted to let you know that the latest pull #62 may have fixed the issue you saw. If you test it out please let me know.

**Comment by Ciobrelis** [comment]
Yes, the issue was solved. However, there are some others. For example in the model: `TRANSFORM.Examples.GenericModular_PWR.Examples.Test`, there is a part `GenericModule PHS
    annotation ();` 
This causes, that the `GenericModule` is not found 
![image](https://user-images.githubusercontent.com/34867742/89709198-19ca0c80-d97e-11ea-9779-03a64e77d1f0.png)

For my understanding this part should look something like this: 

- `TRANSFORM.Examples.GenericModular_PWR.GenericModule PHS annotation ();`

- or should be done by using `import TRANSFORM.xxx`

I copied this **Test** model and implemented these changes and then `GenericModule` is found. 

![image](https://user-images.githubusercontent.com/34867742/89709256-95c45480-d97e-11ea-83b6-6d9825d801ce.png)

However, the model is still not running giving the following error: 

> [5] 13:50:45 Translation Error
[TRANSFORM.Fluid.Machines.Pump_SimpleMassFlow: 17:50-17:71]: Modified element value not found in class Real.

Following the given hyperlink the following line (17) is highlighted: 
`Modelica.Blocks.Interfaces.RealInput in_m_flow(value=m_flow_internal) if
                                                use_input annotation (
      Placement(transformation(
        origin={0,80},
        extent={{-20,-20},{20,20}},
        rotation=270), iconTransformation(
        extent={{-13,-13},{13,13}},
        rotation=270,
        origin={0,73})));` 

The same story with `TRANSFORM.Examples.GenericModular_PWR.Examples.Test2`, where `GenericModule_standAlone PHS` should be replaced with `TRANSFORM.Examples.GenericModular_PWR.GenericModule_standAlone PHS`.  It also gives the previously mentioned error with `TRANSFORM.Fluid.Machines.Pump_SimpleMassFlow`

I am not sure if any of these comments are relevant to you, but if you see it as "noise", please let me know.

**Comment by greenwoodms06** [comment]
I assume this is OpenModelica still.  The models run in Dymola and the file name is valid for Dymola. It seems like it should be for OpenModelica too... that file name is auto-added when dragged in without the full path name. Just the "necessary" aspects of the file name are added as the IDE searches for the file name from the location of the model being run and works its way out.

So we'll be sure to look out for these type of corrections, if necessary, when we reevaluate OpenModelica.

Thank you.
