### ISSUE TITLE
atan22 not found in transform.math.atan22

### ISSUE THREAD

**Issue by veeshy** [ORNL-Modelica/TRANSFORM-Library#63]
When trying to use turboTurbine in a model, got an error:

```
Function TRANSFORM.Math.atan22 is not known in turboTurbine (model TRANSFORM.Fluid.Machines.TurboTurbine).
```

https://github.com/ORNL-Modelica/TRANSFORM-Library/blob/c403dc0ef9542b25939edd01b51b2428aadb6332/TRANSFORM/Fluid/Machines/TurboTurbine.mo#L33

**Comment by jdrader86** [comment]
Hi Vishal.
The turboTurbine component is marked as "under construction." I would suggest not using it at this time. Depending on your application, I would suggest the TRANSFORM.Fluid.Machines.Turbine_SinglePhase_Stodola (for single phase applications) or TRANSFORM.Fluid.Machines.SteamTurbine (for applications where condensing in the turbine may occur).

Thanks,
Jordan

**Comment by veeshy** [comment]
Oh great thanks! I didn't noice that tag, will keep a look out for that next time. Thanks for the rec. Do y'all still prefer issues on things under construction?

**Comment by jdrader86** [comment]
I'll defer to @greenwoodms06 on that, but I would assume issues are OK to post on "under construction" items.
Just understand that we are unlikely to help you fix them unless it's a minor syntactical thing.
I'm actively developing in the turbomachinery library so it's possible that turboTurbine will get some attention in the not-to-distant future. Focusing on the pump side right now.

Also, using "under construction" models is not advised for production work as they are likely candidates for deletion or significant revision. Not sure if there is a project-level description as to what qualifies as "under construction." Once again, maybe @greenwoodms06 can enlighten us.

**Comment by greenwoodms06** [comment]
My initial thoughts... comments are welcome, contributions even more so :), even if that is volunteering to test or provide suggestions on "requirements" for a model under development.

But @jdrader86 is right, under construction is a catch all for things that are not working or at various stages of working and may be moved, deleted, or modified significantly. At some point these models will be moved into a more isolated package so as not to distract from more mature models.
