### ISSUE TITLE
Missing parameters used in Dialog.enable expressions inside annotations

### ISSUE THREAD

**Issue by adrpo** [ORNL-Modelica/TRANSFORM-Library#69]
### Describe the bug
Variables not present in the model are used in Dialog annotations.

### To Reproduce
1. Enable Dymola pedantic mode from Simulation Setup.
2. Navigate to TRANSFORM top directory
3. Right click on TRANSFORM and select Check
4. See the errors in the messages view:
```
Undeclared variable: modelStructure_shell
in the Dialog.enable attribute of steamGenerator.lumpPressureAt_shell declared in class TRANSFORM.HeatExchangers.GenericDistributed_HX
Undeclared variable: modelStructure_tube
in the Dialog.enable attribute of steamGenerator.lumpPressureAt_tube declared in class TRANSFORM.HeatExchangers.GenericDistributed_HX
Undeclared variable: modelStructure
in the Dialog.enable attribute of coreSubchannel.lumpPressureAt declared in class TRANSFORM.Nuclear.CoreSubchannels.Regions_3
```
This happens for TRANSFORM.Nuclear.CoreSubchannels.Regions_1, Regions_2, Regions_3.

### Expected behavior
To check the library without any errors.

### Computer Configuration (please complete the following information):**
 - OS: Windows 10
 - Modelica IDE and version: Dymola 2021

**Comment by greenwoodms06** [comment]
Thank you for mentioning this. This prompted me to go ahead and do a library wide pedantic check. Many issues were fixed with #72.
