### ISSUE TITLE
ExternalMedia test case not functional

### ISSUE THREAD

**Issue by aalfonsi** [ORNL-Modelica/TRANSFORM-Library#88]
### Describe the bug
The example model in ```Media\ExternalMedia\Examples``` errors using the ExternalMedia library (DLL)
from GitHub (https://github.com/modelica-3rdparty/ExternalMedia).

Error:
```
Attempting to redeclare function surfaceTension when the original was not replaceable.
Context: TRANSFORM.Media.ExternalMedia.CoolProp.Hydrogen
In file: path/to/TRANSFORM/Media/ExternalMedia/CoolProp/Hydrogen
```

Can you advice on how to link ExternalMedia with Transform (e.g. re-compilation, etc.)

@veeshy

### Computer Configuration (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Modelica IDE and version: [e.g. Dymola 2020]

**Comment by greenwoodms06** [comment]
which branch of external media are you using? you should be on the MSL4.0 and not master

**Comment by veeshy** [comment]
Any chance you got a link? We didn’t see any 4.0 stuff at https://github.com/modelica-3rdparty/ExternalMedia/branches

**Comment by greenwoodms06** [comment]
yeah it is on my fork: https://github.com/ORNL-Modelica/ExternalMedia/tree/MSL4.0

**Comment by veeshy** [comment]
Awesome! That branch works as expected, thanks for the great work! Good to close (@aalfonsi is in my org fwiw since I didn't init this issue)
