### ISSUE TITLE
TRANSFORM and ExternalMedia are incompatibles

### ISSUE THREAD

**Issue by fentos** [ORNL-Modelica/TRANSFORM-Library#91]
### Describe the bug

Hello,

I am working with Dymola and am looking to use the TRANSFORM library to model a molten salt SMR. I have found an interesting example of CO2 loop in TRANSFORM.Examples.SupercriticalCO2.Examples.SCO2Loop

However this example does not simulate. It seems that some classes have not been imported, especially the ExternalMedia class (located in TRANSFORM.Media) which contains the CO2 related information.

I found on the TRANSFORM github an independent ExternalMedia library which solves this problem. However, it requires Modelica 3.2.1 while TRANSFORM needs Modelica 4.0

So I'm currently stuck. Can you do anything to solve this problem?

### To Reproduce
1. Go to TRANSFORM.Examples.SupercriticalCO2.Examples.SCO2Loop
2. Click on simulate
3. See error

### Computer Configuration (please complete the following information):**
 - OS: Windows 10 Entreprise
 - Modelica IDE and version: Dymola under the 3DEXPERIENCE from DassaultSystem

**Comment by greenwoodms06** [comment]
Probably waaaaay to late. But there is a MSL4.0 branch on this fork of ExternalMedia

https://github.com/ORNL-Modelica/ExternalMedia/tree/MSL4.0

I'd try that.
