### ISSUE TITLE
Pipe flow initialization

### ISSUE THREAD

**Issue by KasparS2** [ORNL-Modelica/TRANSFORM-Library#95]
For component TRANSFORM.Fluid.Pipes.GenericPipe_MultiTransferSurface there is a statement for initial value of port b set as:
p_b_start=p_a_start + (if m_flow_a_start > 0 then -1e3 elseif m_flow_a_start < 0 then -1e3 else 0)
shouldn't it be:
p_b_start=p_a_start + (if m_flow_a_start > 0 then 1e3 elseif m_flow_a_start < 0 then -1e3 else 0)
since if flow is positive pressure would be greater at port b.

**Comment by greenwoodms06** [comment]
positive flow is from a to b. therefore pressure at a is higher than at b. However, you have found an error. It should be:

`p_b_start=p_a_start + (if m_flow_a_start > 0 then -1e3 elseif m_flow_a_start < 0 then 1e3 else 0)`. I have made change and pushed it back to the repo.
